services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 10

  cliente:
    build: ./cliente
    ports:
      - "3001:3001"
    environment:
      PORT: 3001
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: cliente_db
      DB_USER: cliente_user
      DB_PASSWORD: cliente_pass_123
    depends_on:
      postgres:
        condition: service_healthy

  producto:
    build: ./producto
    ports:
      - "3002:3002"
    environment:
      PORT: 3002
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: producto_db
      DB_USER: producto_user
      DB_PASSWORD: producto_pass_123
    depends_on:
      postgres:
        condition: service_healthy

  compra-api:
    build: ./compra-api
    ports:
      - "3003:3003"
    environment:
      PORT: 3003
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: compra_db
      DB_USER: compra_user
      DB_PASSWORD: compra_pass_123
      CLIENTE_API_URL: http://cliente:3001
      PRODUCTO_API_URL: http://producto:3002
    depends_on:
      postgres:
        condition: service_healthy
      cliente:
        condition: service_started
      producto:
        condition: service_started

volumes:
  pgdata:
